; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_s3_devkitm_1

[env:esp32_s3_devkitm_1]
platform = espressif32@6.12.0
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    fastled/FastLED
    Wire
    adafruit/Adafruit BusIO
    adafruit/Adafruit GFX Library
    ESP32 HUB75 LED MATRIX PANEL DMA Display@3.0.14
    bitbank2/AnimatedGIF@^2.2.0
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DESP32_S3_DEVKITM_1
	-DBOARD_HAS_PSRAM
lib_compat_mode = strict
